=== Ashirwad-Mishra/labs/FlexandGrid/student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cse (students)>
<!ELEMENT students (student*)>
<!ELEMENT student (roll , name , batch)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT batch (#PCDATA)>

<!ATTLIST roll eid ID #REQUIRED>

=== Ashirwad-Mishra/labs/FlexandGrid/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cse SYSTEM "student.dtd">

<cse>
    <students>
        <student>
            <roll eid="st1">
                2300320100055
            </roll>
            <name>
                Ashirwad Mishra
            </name>
            <batch>
                2023-27
            </batch>
        </student>
        <student>
            <roll eid="st2">
                2300320100056
            </roll>
            <name>
                Atherve Agrawal
            </name>
            <batch>
                2023-27
            </batch>
        </student>
        <student>
            <roll eid="st3">
                230032010054
            </roll>
            <name>
                Aryan
            </name>
            <batch>
                2023-27
            </batch>
        </student>
    </students>
</cse>
